inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'ruumba/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false
