dist: trusty
language: ruby
cache: bundler
sudo: required
bundler_args: --without production
rvm:
  - 2.4.1

services:
  - mysql

branches:
  only:
    - master
    - develop

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec rails db:setup
  - bundle exec rake keycard:migrate

script:
    - bundle exec rubocop
    - bundle exec rails test
