version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems

  apache:
    build: ./docker/apache
    ports:
      - "80:8080"

volumes:
  gem_cache:
