# Allow users to impersonate (login as) anyone -- useful for development
allow_impersonation: false

# By default don't allow any users to log in
users: []

# How many days away does expiration need to be before we start to worry?
expires_soon_in_days: 30

manager_email: manager@default.invalid
