# Allow users to impersonate (login as) anyone -- useful for development
allow_impersonation: false

# By default don"t allow any users to log in
users: []

# How many days away does expiration need to be before we start to worry?
expires_soon_in_days: 30

manager_email: manager@default.invalid
reply_to_email: reply_to@default.invalid
support_email: support@hathitrust.org

umich_idp: "https://shibboleth.umich.edu/idp/shibboleth"

met_entity_endpoint: "https://met.refeds.org/met/entity"
books_library_endpoint: "https://books.google.com/libraries"
ht_login_test_endpoint: "https://babel.hathitrust.org/Shibboleth.sso/Login?target=https://babel.hathitrust.org/cgi/whoami"

geoip_path: "/usr/src/app/vendor/geoip/GeoIP2-City-Test.mmdb"

# Institution export files
ht_institutions_file: "ht_institutions_test.tsv"
ht_saml_entity_ids_file: "ht_saml_entity_ids_test.tsv"
# Where institutions_export cron job ultimately deposits these files.
export_files_directory: "/usr/src/app/public/"

jira:
  site: https://hathitrust.atlassian.net/
  context_path: ""
  project: GS

# inst_ids with which we relax Shib credential checking in completed registrations.
registration:
  auth_exceptions:
    - nypl

image:
  hathitrust:
    logo:
      name: "hathitrust-logo-horizontal-orange-gray-rgb.png"
      size: "95x25"
    email_signature_logo:
      name: "hathitrust-email-signature-logo.png"
      size: "150x44"
