# Allow users to impersonate (login as) anyone -- useful for development
allow_impersonation: false

# By default don't allow any users to log in
users: []

shibboleth:
  fallback_to_idp: true
  default_idp:
    entity_id: https://shibboleth.umich.edu/idp/shibboleth
  sp:
    url: /Shibboleth.sso
    entity_id: https://hathitrust.org/sp
