allow_impersonation: true
relative_url_root: '/useradmin'

keycard:
  database:
    adapter: sqlite
    database: tmp/keycard_dev.sqlite3

users:
  - somebody@default.invalid

shibboleth:
  fallback_to_idp: true
  default_idp:
    entity_id: https://shibboleth.umich.edu/idp/shibboleth
  sp:
    url: /useradmin/Shibboleth.sso
    entity_id: https://hathitrust.org/sp
