allow_impersonation: true
relative_url_root: '/useradmin'

keycard:
  database:
    adapter: sqlite
    database: tmp/keycard_dev.sqlite3

checkpoint:
  database:
    adapter: sqlite
    database: tmp/checkpoint_dev.sqlite3

# Superuser account
users:
  - admin@default.invalid

# Read-only
staff:
  - staff@default.invalid

# Can view only institutions, not users
institution:
  - institution@default.invalid

shibboleth:
  url: /useradmin/Shibboleth.sso/Login

smtp_host: localhost
