allow_impersonation: true

# Superuser account
users:
  - admin@default.invalid

# Read-only
staff:
  - staff@default.invalid

# Can view only institutions, not users
institution:
  - institution@default.invalid

# Can administer only institution contacts
contact:
  - contact@default.invalid

# relative_url_root doesn't work for tests
relative_url_root: '/'

keycard:
  database:
    adapter: mysql2
    database: ht
    username: otis
    password: otis
    host: mariadb-test

checkpoint:
  database:
    adapter: mysql2
    database: ht
    username: otis
    password: otis
    host: mariadb-test

shibboleth:
  url: /useradmin/Shibboleth.sso/Login
