allow_impersonation: true

# How many days away does expiration need to be before we start to worry?
expires_soon_in_days: 30

users:
- nobody@example.com

# relative_url_root doesn't work for tests
relative_url_root: '/'

keycard:
  database:
    adapter: sqlite
    database: tmp/keycard_test.sqlite3
