name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to Production
      uses: mlibrary/deploy-to-kubernetes@v1
      with:
        github_username: ${{ github.actor }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/hathitrust/otis:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.KUBERNETES_CA }} ### DONE
        cluster_server: ${{ secrets.KUBERNETES_SERVER }} ### DONE
        namespace_token: ${{ secrets.KUBERNETES_TOKEN_PROD }} ### DONE
        namespace: otis ### DONE
