name: Deploy

on:
    workflow_dispatch:
        inputs:
            branch_hash:
                description: Branch sha or revision to deploy (Defaults to branch sha)
            environments:
                description: The environment to deploy to
                type: choice
                default: testing
                options:
                - testing
                - staging
                - production

jobs:
    deploy:
            runs-on: ubuntu-latest
            permissions:
                contents: read
                packages: write
            steps:
                - name: Deploy to ${{inputs.environments}}
                  uses: hathitrust/github_actions/deploy@v1
                  with:
                    image: ghcr.io/${{ github.repository }}:${{ inputs.branch_hash || github.sha}}
                    file: environments/${{ github.event.repository.name }}/${{inputs.environments}}/otis-image.txt
                    CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
                    CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
                    CONFIG_REPO_RW_KEY: ${{secrets.CONFIG_REPO_RW_KEY}}
