name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to ${{ env.environment }}
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ github.token }}
        image: ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.KUBERNETES_CA }}
        cluster_server: ${{ secrets.KUBERNETES_SERVER }}
        namespace_token: ${{ secrets.KUBERNETES_TOKEN }}
        namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
    # Additional config for cronjob; we could do this using labels & a
    # single call to the action, but those labels are not set up in
    # kubernetes yet
    - name: Deploy daily-digest Cronjob to Production
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.KUBERNETES_CA }}
        cluster_server: ${{ secrets.KUBERNETES_SERVER }}
        namespace_token: ${{ secrets.KUBERNETES_TOKEN }}
        namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
        resource_type: cronjob
        resource_name: daily-digest
