name: Deploy to Testing

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true
  workflow_run:
    workflows: [ 'Docker Build Master' ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone latest repository
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check that the tag exists
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: tag_check
      run: |
        if git rev-parse 'refs/tags/${{ github.event.inputs.tag }}' &> /dev/null; then
          echo '::set-output name=tag::${{ github.event.inputs.tag }}'
        elif git rev-parse '${{ github.event.inputs.tag }}' &> /dev/null; then
          echo "::set-output name=tag::`git rev-parse '${{ github.event.inputs.tag }}'`"
        else
          echo "Couldn't figure out tag from input: ${{ github.event.inputs.tag }}"
          echo "Aborting deployment."
          false
        fi
    - uses: azure/setup-kubectl@v1
    - name: Authenticate with kubernetes
      run: |
        mkdir -p ${HOME}/.kube/certs/cluster
        echo ${{ secrets.KUBERNETES_CA }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
        kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=${{ secrets.KUBERNETES_SERVER }}
        kubectl config set-credentials default --token=`echo ${{ secrets.KUBERNETES_TOKEN }} | base64 -d`
        kubectl config set-context default --cluster=cluster --user=default --namespace=otis-testing
        kubectl config use-context default
    - name: Automatic Deploy
      if: ${{ github.event_name == 'workflow_run' }}
      run: |
        kubectl set image deployment web web=hathitrust/otis-unstable:${{ github.sha }}
    - name: Manual Deploy
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        kubectl set image deployment web web=hathitrust/otis-unstable:${{ steps.tag_check.outputs.tag }}
