name: Deploy

on:
    workflow_dispatch:
        inputs:
            branch_hash:
                description: Branch sha or revision to deploy (Defaults to branch sha)
            environments:
                description: The environment to deploy to
                type: choice
                default: testing
                options:
                - testing
                - staging
                - production


jobs:
    deploy:
        permissions:
            contents: read
            packages: write
        name: Deploy to ${{inputs.environments}}
        uses: hathitrust/github_actions/.github/workflows/deploy.yml@2936af20240b3438cd0694fdd0e598b52ced1324 # v2.0.1
        with:
            image: ghcr.io/${{ github.repository }}:${{ inputs.branch_hash || github.sha}}
            file: environments/${{ github.event.repository.name }}/${{inputs.environments}}/otis-image.txt
            CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
        secrets: inherit
