name: Docker Tag Latest Release

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Clone latest repository
      uses: actions/checkout@v2
    - name: Tag latest release in GHCR
      run: |
        docker pull ghcr.io/hathitrust/otis-unstable:${{ github.sha }}
        docker tag ghcr.io/hathitrust/otis-unstable:${{ github.sha }} ghcr.io/hathitrust/otis:${{ github.event.release.tag_name }}
        docker tag ghcr.io/hathitrust/otis-unstable:${{ github.sha }} ghcr.io/hathitrust/otis:latest
        docker push ghcr.io/hathitrust/otis:${{ github.event.release.tag_name }}
        docker push ghcr.io/hathitrust/otis:latest
