name: Docker Tag Latest Release

on:
  release:
    types: [ released ]

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Clone latest repository
      uses: actions/checkout@v2
    - name: Tag latest release in GHCR
      env:
        UNSTABLE_IMAGE_ID: ghcr.io/hathitrust/otis-unstable
        PROD_IMAGE_ID: ghcr.io/hathitrust/otis
      run: |
        docker pull $UNSTABLE_IMAGE_ID:${{ github.sha }}
        docker tag $UNSTABLE_IMAGE_ID:${{ github.sha }} $PROD_IMAGE_ID:${{ env.TAG }}
        docker tag $UNSTABLE_IMAGE_ID:${{ github.sha }} $PROD_IMAGE_ID:latest
        docker push $PROD_IMAGE_ID:${{ env.TAG }}
        docker push $PROD_IMAGE_ID:latest
