name: Tag Latest Image with Release Version

on:
  release:
    types: [released]

jobs:
  tag-release:
    name: Tag Release
    uses: hathitrust/github_actions/.github/workflows/tag-release.yml@01b5414ee8d41485319b355b347002d269d42d30 # v2.0.0
    with:
      existing_tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
      image: ghcr.io/${{ github.repository }}
      new_tag: ${{ github.event.release.tag_name }}
    secrets: inherit

