name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up tests
        run: |
          docker compose build
          docker compose run test bundle install

      - name: Run standardrb
        run: docker compose run test bundle exec standardrb

      - name: Run i18n-tasks health
        run: docker compose run test bundle exec i18n-tasks health

      - name: Run tests
        run: docker compose run test

      - name: Report to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: unit
          parallel: true

      - name: Run system tests
        run: docker compose run system-test

      - name: Report to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: integration
          parallel: true

      - name: Coveralls Finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: integration
          parallel-finished: true
