name: Run Tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up tests
        run: |
          docker-compose build
          docker-compose run test bundle install

      - name: Run standardrb
        run: docker-compose run test bundle exec standardrb

      - name: Run tests
        run: docker-compose run test

